name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # On donne la permission au script de créer une Release sur GitHub
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Cache Android debug keystore
      uses: actions/cache@v4
      with:
        path: ~/.android/debug.keystore
        key: debug-keystore-${{ runner.os }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.7'

    - name: Get SHA-1 Fingerprint
      run: gradle signingReport
      working-directory: ./CortexAndroidApp

    - name: Build with Gradle
      run: gradle assembleDebug
      working-directory: ./CortexAndroidApp

    - name: Publier sur la page Releases (Pas de quota)
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "v1.2.1"
        name: "Cortex AI(Application Android)"
        body: "Téléchargez l'application Cortex IA directement depuis cette page !"
        files: CortexAndroidApp/app/build/outputs/apk/debug/app-debug.apk
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
